import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/app//Components/Header"
const inter = Inter({ subsets: ['latin'] })
import { Mulish } from 'next/font/google';
 
const MullishFont = Mulish({
  weight: ['300','400','500','600','700','800','900'],
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (<>
    
    <html lang="en" className={MullishFont.className}>
   
      <body suppressHydrationWarning={true}>
        <div>
        <Header></Header>
        </div>
        <div>{children}</div></body>
    </html>
    </>
  )
}
